import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { reviewStatusFixture } from './review-status-helpers.ts';
import { retainProjectFile } from '../extensions/utils/retention.ts';

const jobIds = (root: string) => fs.readdirSync(path.join(root, '.pnw/jobs')).filter(f => /^[0-9a-f-]{36}\.json$/.test(f)).map(f => f.slice(0, -5));
test('M11: successful and failed audits expose status without fictional scene checkpoints', async () => {
  const f = await reviewStatusFixture();
  Object.assign(f.ctx, f.auditWorker);
  await f.command('authorize 2 300000');
  const successful = JSON.parse((await f.pi.call('novel_literary_audit', { scope: { level: 'chapter', chapter: 1 }, review: true }, f.ctx)).content[0].text);
  const id = successful.audit.key.slice('audit:'.length);
  assert.equal(fs.existsSync(path.join(f.root, `.pnw/jobs/${id}.pipeline.json`)), false);
  const done = await f.status(id);
  assert.equal(done.kind, 'sequence-audit');
  assert.equal(done.stage, 'accepted');
  assert.equal(done.auditRecord.hash, successful.audit.hash);
  assert.equal(done.privateCheckpoint, undefined);
  assert.equal(done.candidateWords, undefined);
  const known = new Set(jobIds(f.root));
  f.ctx.modelRegistry = { complete: async () => { throw new Error('Simulated audit transport failure'); } };
  await f.command('authorize 1 300000');
  await assert.rejects(f.pi.call('novel_literary_audit', { scope: { level: 'manuscript' }, review: true }, f.ctx), /failure|failed/i);
  const failedId = jobIds(f.root).find(id => !known.has(id))!;
  const failed = await f.status(failedId);
  assert.equal(failed.kind, 'sequence-audit');
  assert.equal(failed.stage, 'blocked');
  assert.equal(failed.auditRecord, null);
  assert.equal(failed.job.reservations[0].status, 'failed');
  assert.equal((await f.status(f.sceneJob)).kind, 'scene');
  const checkpoint = path.join(f.root, `.pnw/jobs/${f.sceneJob}.pipeline.json`);
  retainProjectFile(f.root, checkpoint, 'Simulated missing scene checkpoint');
  await assert.rejects(f.status(f.sceneJob), /ENOENT|checkpoint/);
});

test('M11: interrupted audit execution recovery and call inspection return honest audit status', async () => {
  const f = await reviewStatusFixture(), known = new Set(jobIds(f.root));
  const child = spawnSync(process.execPath, ['--experimental-strip-types', fileURLToPath(new URL('./recovery-child.mjs', import.meta.url)), 'audit', f.root, JSON.stringify({ level: 'manuscript' })], { encoding: 'utf8' });
  console.log(JSON.stringify({ crash: 'audit', pid: child.pid, status: child.status, stderr: child.stderr }));
  assert.equal(child.status, 23, child.stderr);
  assert.throws(() => process.kill(child.pid!, 0), (e: any) => e.code === 'ESRCH');
  const id = jobIds(f.root).find(id => !known.has(id))!;
  const pending = await f.status(id);
  assert.equal(pending.kind, 'sequence-audit');
  assert.equal(pending.stage, 'running');
  assert.equal(pending.executionLock.pid, child.pid);
  assert.equal(pending.job.reservations[0].status, 'pending');
  await f.command(`recover-job ${id} ${pending.executionLock.token}`);
  const recovered = JSON.parse((f.pi.messages.at(-1) as any).content);
  assert.equal(recovered.kind, 'sequence-audit');
  assert.equal(recovered.executionLock, null);
  assert.equal(recovered.job.reservations[0].status, 'pending');
  await f.command(`inspect ${id} Confirmed stopped synthetic audit; preserve unknown usage`);
  const inspected = JSON.parse((f.pi.messages.at(-1) as any).content);
  assert.equal(inspected.stage, 'paused');
  assert.equal(inspected.auditRecord, null);
  assert.equal(inspected.job.reservations[0].status, 'failed');
  assert.equal(inspected.job.reservations[0].reservedTokens, pending.job.reservations[0].reservedTokens);
  fs.writeFileSync(path.join(f.root, 'status-fixture.json'), JSON.stringify({ synthetic: true, interruptedAuditId: id, sceneJobId: f.sceneJob }), { flag: 'wx' });
});
